const fields = [
  ['services','Completed services','Count',10000],
  ['price','Average net service price','IDR',1000000000000],
  ['opening-cash','Opening cash','IDR',1000000000000],
  ['cash-receipts','Cash receipts','IDR',1000000000000],
  ['digital-receipts','Digital receipts','IDR',1000000000000],
  ['cash-expenses','Cash expenses','IDR',1000000000000],
  ['actual-cash','Actual closing cash','IDR',1000000000000],
] as const
export function barberContent() {
  return `<header class="page-hero"><p class="eyebrow">HOLBERY / Systems / research toolkit v0.1</p><h1>Close the day.<br>Understand the work.</h1><p>A small daily-close workflow for barber operators. Use the calculator, record the close, and review what needs an explanation.</p><span class="tag">EXPERIMENT — OPERATOR VALIDATION PENDING</span></header>
<section class="tool-panel" aria-labelledby="calculator-heading"><p class="eyebrow">Browser-only / no account required</p><h2 id="calculator-heading">Daily-close calculator</h2><p>Enter whole, non-negative IDR values. All fields are required; enter 0 when appropriate. These inputs are not saved or sent to a server.</p><form id="daily-close-form" novalidate><section class="tool-form">${fields.map(([id,label,unit,max])=>`<section class="field"><label for="${id}">${label} (${unit})</label><input id="${id}" name="${id}" type="number" min="0" max="${max}" step="1" inputmode="numeric" required autocomplete="off"></section>`).join('')}</section><button class="button button-primary" type="submit">Calculate daily close</button> <button class="button" type="reset">Clear inputs</button><p id="calculator-error" class="tool-error" role="alert"></p></form><section id="calculation-result" class="tool-output" aria-live="polite" aria-label="Daily close result" tabindex="-1" hidden></section><small>This simple workflow excludes refunds, tips, discounts, owner withdrawals, commissions, credit sales and tax/accounting adjustments. Average price should reflect the net service value being compared. Receipts less cash expenses is NOT profit. Investigate differences; do not assume the cause.</small></section>
<section class="content-grid"><h2>The workflow.<br>Not another giant platform.</h2><section><p>Count completed services. Record receipts and cash. Reconcile the close. Explain differences. Choose a next action.</p><p>Expected service revenue = count × average net price. Receipt gap = cash + digital receipts − expected service revenue. Expected cash = opening cash + cash receipts − cash expenses. Cash discrepancy = actual cash − expected cash.</p><p>Start with one responsible closer and a single location. Store actual records privately under your control. No CRM, bookings, customer database, payment collection, or reminders are included.</p></section></section>
<section class="principles-section"><p class="eyebrow">Ready to try, not proven results</p><h2>Take the routine<br>into the working day.</h2><p>Blank templates and a printable checklist. No synthetic sample is presented as a real business record.</p><section class="download-list"><a class="button button-primary" href="/downloads/daily-close.csv" download>Daily-close CSV <span aria-hidden="true">↓</span></a><a class="button" href="/downloads/weekly-review.csv" download>Weekly-review CSV <span aria-hidden="true">↓</span></a><a class="button" href="/downloads/barber-onboarding.html">Printable onboarding <span aria-hidden="true">↗</span></a></section><p>Real operator pilots and willingness-to-pay testing have not yet been completed. The toolkit is a free research resource; guided implementation is not being sold through this page.</p></section>
<section class="contact-strip"><section><h2>Help test the real workflow.</h2><p>Operator research needs an accountable owner and a private contact channel.<br>Do not publish business figures or customer information in public enquiries.</p></section><a class="button button-primary" href="/contact">Discuss a pilot <span aria-hidden="true">↗</span></a></section><script type="module" src="/static/barber.js"></script>`
}
