import { Hono } from 'hono'
import { secureHeaders } from 'hono/secure-headers'
import { serveStatic } from 'hono/cloudflare-workers'

export const app = new Hono()
// Canonical host remains the verified deployment host until the strategic domain is under control.
const origin = 'https://webapp-4.pages.dev'
const repo = 'https://github.com/Sparkmind-obp-off/Holbery'
const nav = [['About','/about'],['Systems','/systems'],['Products','/products'],['Ventures','/ventures'],['Commerce','/commerce']]
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))
app.use('*', secureHeaders({
  contentSecurityPolicy: { defaultSrc: ["'self'"], scriptSrc: ["'self'"], styleSrc: ["'self'"], imgSrc: ["'self'", 'data:'], fontSrc: ["'self'"], connectSrc: ["'self'"], objectSrc: ["'none'"], baseUri: ["'self'"], frameAncestors: ["'none'"], formAction: ["'self'"] },
  referrerPolicy: 'strict-origin-when-cross-origin',
  permissionsPolicy: { camera: [], microphone: [], geolocation: [] }
}))
app.get('/api/health', c => c.json({ status: 'ok', brand: 'HOLBERY', version: '1.1.0' }))
app.get('/robots.txt', c => c.text(`User-agent: *\nAllow: /\nDisallow: /api/\nSitemap: ${origin}/sitemap.xml\n`))
app.get('/sitemap.xml', c => c.body(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/','/about','/systems','/products','/ventures','/commerce','/contact','/docs','/privacy'].map(p=>`<url><loc>${origin}${p}</loc></url>`).join('')}</urlset>`,200,{'Content-Type':'application/xml'}))
app.use('/static/*', serveStatic({root:'./public'}))
app.use('/downloads/*', serveStatic({root:'./public'}))

function layout(path: string, title: string, description: string, body: string) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#33462f"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="index,follow"><link rel="canonical" href="${origin}${path}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${origin}${path}"><meta property="og:image" content="${origin}/static/og-card.svg"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" href="/static/favicon.svg"><link rel="stylesheet" href="/static/style.css"><script src="/static/site.js" defer></script></head><body><a class="skip-link" href="#main-content">Skip to content</a><header class="site-header"><a class="brand" href="/" aria-label="HOLBERY home"><img src="/static/favicon.svg" width="30" height="30" alt=""><span>HOLBERY</span></a><button class="menu-toggle" aria-controls="primary-navigation" aria-expanded="false" type="button">Menu <span aria-hidden="true">+</span></button><nav id="primary-navigation" aria-label="Main navigation">${nav.map(([label,url])=>`<a href="${url}" ${path===url?'aria-current="page"':''}>${label}</a>`).join('')}<a class="nav-contact" href="/contact" ${path==='/contact'?'aria-current="page"':''}>Let's connect <span aria-hidden="true">↗</span></a></nav></header><main id="main-content">${body}</main><footer class="site-footer"><section class="footer-intro"><a class="brand" href="/">HOLBERY</a><p>Useful things. Clear operations.<br>Room to grow.</p></section><nav aria-label="Footer navigation"><a href="/about">The parent</a><a href="/docs">Our approach</a><a href="/contact">Contact</a><a href="/privacy">Privacy</a></nav><p class="footer-note">© ${new Date().getUTCFullYear()} HOLBERY<br>A parent ecosystem, built step by step.</p></footer></body></html>`
}
const arrow = '<span aria-hidden="true">↗</span>'
const pillars = [
  {n:'01',name:'Systems',url:'/systems',intro:'Make the work work.',text:'Practical software, workflows, and operational tools for the way businesses actually run.'},
  {n:'02',name:'Products',url:'/products',intro:'Useful. Ready to use.',text:'Digital resources, physical products, and packaged solutions with a clear purpose.'},
  {n:'03',name:'Ventures',url:'/ventures',intro:'Ideas into operations.',text:'Businesses we develop and operate, with demand, ownership, and economics at the center.'},
  {n:'04',name:'Commerce',url:'/commerce',intro:'Value, within reach.',text:'Distribution, partnerships, and channels that connect useful offers with the right customers.'}
]
function pillarCards() { return pillars.map(p=>`<a class="pillar-card" href="${p.url}"><span class="card-index">${p.n} / ${p.name.toUpperCase()}</span><h3>${p.intro}</h3><p>${p.text}</p><span class="card-link">Explore ${p.name.toLowerCase()} ${arrow}</span></a>`).join('') }
app.get('/', c=>c.html(layout('/','HOLBERY — Build. Operate. Grow.','Practical systems, products, and ventures. HOLBERY is the parent ecosystem for building useful things and operating with clarity.',`
<section class="home-hero"><section class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> A practical parent ecosystem</p><h1>Build.<br>Operate.<br><em>Grow.</em></h1><p class="hero-description">Practical systems, products, and ventures.<br>Built for real work. Designed to grow.</p><a class="button button-primary" href="#ecosystem">Explore the ecosystem ${arrow}</a><a class="quiet-link" href="/about">What is HOLBERY? <span aria-hidden="true">→</span></a></section><figure class="ecosystem-figure"><figcaption><span>THE HOLBERY STRUCTURE</span><span>ONE PARENT. MANY POSSIBILITIES.</span></figcaption><img src="/static/ecosystem.svg" width="560" height="500" alt="HOLBERY is the parent of four connected pillars: Systems, Products, Ventures, and Commerce."><p>Different directions.<br><strong>One clear foundation.</strong></p></figure></section>
<section class="statement-section"><p class="eyebrow">The parent, not the limit</p><h2>A foundation for<br>what comes next.</h2><p>HOLBERY brings structure to building and operating useful businesses. Not one product. Not one industry. A clear home for work that earns its place in the real world.</p></section>
<section id="ecosystem" class="ecosystem-section"><header class="section-heading"><section><p class="eyebrow">Our ecosystem</p><h2>Four pillars.<br>Room to build.</h2></section><p>Each with a purpose.<br>All under one parent.</p></header><section class="pillar-grid">${pillarCards()}</section></section>
<section class="approach-section"><p class="eyebrow">How we move</p><h2>Start with a real problem.<br>Grow from real proof.</h2><ol class="approach-steps"><li><span>01</span><h3>Discover & validate</h3><p>Understand the work. Test whether the problem is worth solving.</p></li><li><span>02</span><h3>Build & operate</h3><p>Create the smallest useful solution. Put it into practice.</p></li><li><span>03</span><h3>Measure & improve</h3><p>Learn from outcomes. Scale only what proves its value.</p></li></ol><a class="text-link" href="/docs">Read our operating approach ${arrow}</a></section>
<section class="focus-section"><section><p class="eyebrow">First development focus</p><h2>Better daily operations.<br>Starting with barber businesses.</h2><p>Our first system explores a simple challenge: making a working day easier to close, understand, and improve.</p><a class="text-link" href="/systems">Explore our first system ${arrow}</a></section><aside class="focus-note"><span class="tag">IN DEVELOPMENT</span><p>One workflow.<br>One real-world test.<br>Then the next step.</p><small>No proven-results claims before an operator pilot.</small></aside></section>
<section class="contact-strip"><h2>Useful work starts<br>with a conversation.</h2><a class="button button-primary" href="/contact">Let's connect ${arrow}</a></section>`)))
const pageHero = (eyebrow:string,title:string,description:string)=>`<header class="page-hero"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></header>`
app.get('/about',c=>c.html(layout('/about','About HOLBERY — The parent, not the limit','A parent ecosystem for practical businesses, systems, products, and ventures.',`${pageHero('What is HOLBERY','The parent.<br>Not the limit.','We build useful things, operate with clarity, and grow with proof.')}<section class="content-grid"><h2>A home for practical<br>business building.</h2><section><p>HOLBERY is a parent ecosystem. It can develop, operate, productize, and distribute work across systems, products, ventures, and commerce.</p><p>Technology is a tool. A product is an offer. A venture is a business. None of them defines the whole parent.</p><p>Our starting point is simple: understand a real problem, create a practical solution, and earn the right to grow.</p></section></section><section class="principles-section"><h2>What we stand for.</h2><section class="three-column"><article><h3>Clarity first</h3><p>Clear scope, accountable ownership, and honest status. No corporate theatre.</p></article><article><h3>Reality first</h3><p>Customer use, operator feedback, and sustainable economics outrank theoretical scale.</p></article><article><h3>Proof before growth</h3><p>Useful outcomes and repeatable delivery come before more products, brands, or verticals.</p></article></section></section><section class="contact-strip"><p>Different businesses can grow underneath HOLBERY.<br>They do not all need the same customer-facing name.</p><a class="text-link" href="/docs">Our approach ${arrow}</a></section>`)))
for (const p of pillars) app.get(p.url,c=>c.html(layout(p.url,`${p.name} — HOLBERY`,p.text,`${pageHero(`HOLBERY / ${p.name}`,p.intro,p.text)}<section class="content-grid"><h2>${p.name==='Systems'?'Make daily work<br>more dependable.':p.name==='Products'?'Package value.<br>Make it repeatable.':p.name==='Ventures'?'Build the business.<br>Not just the idea.':'Connect the offer.<br>Deliver the value.'}</h2><section><p>${p.name==='Systems'?'Our first development direction is a Barber Business System: a small, practical workflow for daily closing, revenue clarity, and operator decisions. It is an experiment, not a proven SaaS.':p.name==='Products'?'Products can be digital or physical. We begin with a clear customer, problem, outcome, and delivery method. A daily-close operations kit is our first productization direction, pending operator validation.':p.name==='Ventures'?'A venture needs an accountable operator, distinct customer value, and its own economics. No operated venture is being claimed here today. We will introduce them only when ownership and operating evidence support it.':'Commerce is the distribution layer, not a claim that a marketplace is already operating. We begin with a direct channel and accountable fulfillment. Partners, affiliates, and wider channels follow proven demand.'}</p><span class="tag">${p.name==='Systems'?'DEVELOPMENT FOCUS':'FRAMEWORK ESTABLISHED'}</span><p class="muted">Availability follows validation. No customer logos, revenue figures, or performance promises are implied.</p><a class="text-link" href="${p.name==='Systems'?'/systems/barber':'/contact'}">${p.name==='Systems'?'View the pilot toolkit':'Discuss this direction'} ${arrow}</a></section></section><section class="principles-section"><p class="eyebrow">Our standard</p><h2>Clear customer. Useful outcome.<br>Repeatable delivery.</h2><a class="text-link" href="/docs">How we build ${arrow}</a></section>`)))
app.get('/contact',c=>c.html(layout('/contact','Contact — HOLBERY','Start a conversation about practical systems, products, ventures, or partnerships.',`${pageHero('Let’s connect','Start with<br>the real work.','Tell us about the problem, the operator, and the outcome you want to improve.')}<section class="content-grid"><h2>A clear starting point.</h2><section><p>We welcome conversations about operator research, pilot workflows, product ideas, and practical partnerships.</p><a class="button button-primary" href="${repo}/issues/new?title=HOLBERY%20enquiry" rel="noopener noreferrer" target="_blank">Open a GitHub enquiry ${arrow}</a><p class="contact-notice">This is a public GitHub channel and requires a GitHub account. Do not post customer data, private business figures, credentials, or confidential material.</p><p>A private business email channel has not been verified yet. We do not collect contact-form submissions on this site.</p><a class="text-link" href="${repo}" rel="noopener noreferrer" target="_blank">Visit the HOLBERY repository ${arrow}</a></section></section>`)))
app.get('/docs',c=>c.html(layout('/docs','Our approach — HOLBERY','A practical operating loop and clear governance for building useful businesses.',`${pageHero('Public documentation','A method.<br>Not a maze.','Simple rules, repeatable work, and clear decisions.')}<section class="principles-section"><h2>The operating loop</h2><ol class="operating-loop">${['Discover','Validate','Design','Build','Launch','Operate','Measure','Improve','Scale'].map((s,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${s}</li>`).join('')}</ol><p>Every project starts with a customer problem and an accountable owner. Every meaningful transition needs evidence. Live software is not customer validation.</p></section><section class="content-grid"><h2>One parent.<br>Four clear pillars.</h2><section><p>Systems make work repeatable. Products package value. Ventures operate businesses. Commerce connects them to customers.</p><p>We choose one primary category per project. Shared capabilities are reused when real patterns repeat, not built speculatively.</p><p>Our first pilot explores daily closing in barber businesses. Operational use and commercial demand remain to be validated.</p><a class="text-link" href="/systems/barber">Explore the pilot toolkit ${arrow}</a></section></section>`)))
app.get('/privacy',c=>c.html(layout('/privacy','Privacy — HOLBERY','How this lightweight HOLBERY website handles data.',`${pageHero('Privacy / updated 5 October 2026','A small site.<br>A clear data boundary.','We do not run a customer database or collect contact-form submissions on this site.')}<section class="prose"><h2>Site requests</h2><p>Cloudflare delivers this website and may process request metadata such as IP address, user agent, time, and security events under its service policies. Operational account metrics are not a customer analytics database.</p><h2>Cookies and analytics</h2><p>No marketing cookies, third-party analytics scripts, or advertising trackers are configured by this application. Cloudflare security features may operate at the hosting layer.</p><h2>Downloads and calculator</h2><p>Toolkit files are downloaded to your device. Calculator inputs are processed in your browser, are not saved by the site, and are not submitted to a server. Do not enter identifiable customer information.</p><h2>External contact</h2><p>GitHub enquiries are public and handled under GitHub’s policies. Do not submit sensitive information. A verified private email and formal privacy contact are pending owner confirmation.</p><h2>Scope and review</h2><p>This is an informational site, not a payment or customer-management service. Before introducing accounts, forms, customer records, or analytics we will review the data purpose, lawful basis, retention, consent, and contact arrangements.</p></section>`)))
app.get('/systems/barber', c=>c.html(layout('/systems/barber','Barber Business System — HOLBERY','A practical daily-close workflow for barber operators, in development.',`${pageHero('Systems / first development focus','Close the day.<br>Understand the work.','A practical Barber Business System, starting with a simple daily-close workflow.')}<section class="content-grid"><h2>Small enough to use.<br>Clear enough to test.</h2><section><span class="tag">EXPERIMENT — NOT VALIDATED</span><p>We begin with service totals, receipts, expenses, and cash reconciliation. Operator interviews and a real pilot are still required before performance or market-fit claims.</p><p>The pilot toolkit is being prepared. It does not include accounts, customer records, payments, or a giant SaaS platform.</p><a class="text-link" href="/contact">Discuss operator research ${arrow}</a></section></section>`)))
// Explicit catch-all avoids adapter reliance on Hono's private notFoundHandler property.
app.all('*',c=>c.html(layout('/404','Page not found — HOLBERY','This page is not available.',`${pageHero('404','A different direction.','The page you are looking for is not here.')}<section class="prose"><a class="button button-primary" href="/">Back to HOLBERY ${arrow}</a></section>`),404))
export { layout, pageHero }
export default app
