export const toolDefinitions = [
 {id:'daily_close',slug:'daily-close',title:'Kalkulator Daily Close Barber',description:'Hitung penutupan harian barber: cocokkan omzet layanan, penerimaan tunai/digital, dan saldo kas. Gratis tanpa akun.',intro:'Tutup hari.<br>Pahami selisihnya.',formId:'daily-close-form',fields:[['services','Jumlah layanan selesai','services',10000],['price','Harga rata-rata bersih jasa (Rp)','price',1e12],['opening-cash','Kas awal (Rp)','openingCash',1e12],['cash-receipts','Penerimaan tunai (Rp)','cashReceipts',1e12],['digital-receipts','Penerimaan digital (Rp)','digitalReceipts',1e12],['cash-expenses','Pengeluaran tunai (Rp)','cashExpenses',1e12],['actual-cash','Kas akhir aktual (Rp)','actualCash',1e12]],explanation:'Omzet layanan = jumlah layanan × harga rata-rata bersih. Selisih penerimaan = tunai + digital − omzet layanan. Kas seharusnya = kas awal + penerimaan tunai − pengeluaran tunai. Selisih kas = aktual − seharusnya.',limits:'Tidak mencakup refund, tip, penarikan pemilik, komisi, kredit, pajak atau penyesuaian akuntansi. Penerimaan dikurangi pengeluaran tunai BUKAN laba.',example:'Contoh ilustratif: 10 layanan × Rp30.000 = Rp300.000. Tunai Rp200.000 + digital Rp100.000 cocok dengan omzet. Kas awal Rp100.000, pengeluaran Rp50.000, kas akhir Rp250.000 berarti selisih kas nol.',faq:'Apakah selisih kas berarti kerugian atau fraud?',answer:'Tidak. Selisih harus dijelaskan dengan catatan operasional; kalkulator tidak menentukan penyebab atau laba.'},
 {id:'target_revenue',slug:'target-omzet',title:'Kalkulator Target Omzet Barber',description:'Berapa potong rambut per hari untuk target omzet bulanan? Hitung target layanan dan omzet harian gratis tanpa registrasi.',intro:'Target omzet.<br>Jadi target harian.',formId:'target-revenue-form',fields:[['target','Target omzet bulanan (Rp)','target',1e12],['price','Harga rata-rata bersih per layanan (Rp)','price',1e12],['days','Hari buka dalam bulan','days',31]],explanation:'Layanan bulanan = pembulatan ke atas target ÷ harga rata-rata. Target layanan per hari = pembulatan ke atas layanan bulanan ÷ hari buka. Target omzet harian = target bulanan ÷ hari buka.',limits:'Omzet bukan laba. Satu layanan diasumsikan satu cut; jumlah pelanggan unik tidak diketahui. Hari buka 1–31, harga harus lebih besar dari nol. Target bukan jaminan permintaan atau kapasitas.',example:'Contoh ilustratif: target Rp10.000.000, harga Rp25.000, buka 25 hari → 400 layanan per bulan atau 16 layanan per hari. Periksa apakah kapasitas dan permintaan mendukung.',faq:'Apakah 16 layanan berarti 16 pelanggan unik?',answer:'Belum tentu. Hasil menghitung layanan berdasarkan harga rata-rata, bukan identitas pelanggan atau bukti demand.'},
 {id:'break_even',slug:'break-even',title:'Kalkulator Break-even Barbershop',description:'Hitung berapa layanan barber untuk impas dari biaya tetap dan margin kontribusi per layanan. Gratis tanpa akun.',intro:'Ketahui biaya.<br>Hitung titik impas.',formId:'break-even-form',fields:[['fixed','Biaya tetap bulanan (Rp)','fixed',1e12],['price','Harga bersih per layanan (Rp)','price',1e12],['variable','Biaya variabel per layanan (Rp)','variable',1e12],['days','Hari buka dalam bulan','days',31]],explanation:'Kontribusi per layanan = harga bersih − biaya variabel per layanan. Layanan impas bulanan = pembulatan ke atas biaya tetap ÷ kontribusi. Layanan impas per hari = pembulatan ke atas layanan bulanan ÷ hari buka.',limits:'Gunakan biaya sesuai periode dan hindari menghitung biaya yang sama dua kali. Komisi per layanan dapat termasuk biaya variabel; sewa biasanya biaya tetap. Jika harga ≤ biaya variabel, tidak ada titik impas yang bisa dihitung dengan margin positif. Bukan nasihat akuntansi/pajak.',example:'Contoh ilustratif: biaya tetap Rp3.000.000, harga Rp30.000, biaya variabel Rp10.000, buka 25 hari → kontribusi Rp20.000, 150 layanan per bulan, 6 per hari untuk menutup biaya tetap.',faq:'Apakah impas berarti bisnis pasti sehat?',answer:'Tidak. Model sederhana ini tidak menjamin demand, kapasitas, cash flow, pajak, atau seluruh biaya sudah tercatat.'}
] as const
export type ToolId = typeof toolDefinitions[number]['id']
export function toolsHub() {
 return `<header class="page-hero"><p class="eyebrow">HOLBERY / Free Tools</p><h1>Jawaban kecil.<br>Manfaat yang nyata.</h1><p>Kalkulator bisnis gratis, tanpa akun, tanpa meminta data pribadi. Mulai dari tiga pekerjaan barber yang perlu dihitung—bukan 30 tool sekaligus.</p></header><section class="principles-section"><p class="eyebrow">Barber / 3 utility awal</p><section class="three-column">${toolDefinitions.map(t=>`<article class="utility-card"><span class="tag">GRATIS · TANPA AKUN</span><h2>${t.title}</h2><p>${t.description}</p><a class="button button-primary" href="/tools/barber/${t.slug}" data-next-tool="${t.id}">Gunakan gratis <span aria-hidden="true">↗</span></a></article>`).join('')}</section></section><section class="content-grid"><h2>Gratis untuk menghitung.<br>Sistem untuk menjalankan.</h2><section><p>Utility membantu Anda memahami angka. Sistem berbayar membantu pekerjaan berulang, review dan implementasi. Kami tidak menganggap kunjungan atau klik sebagai bukti hasil bisnis.</p><p>Pricing, simulator kenaikan harga, dan diagnostic belum dibangun. Penggunaan nyata menentukan langkah berikutnya.</p><a class="text-link" href="/products">Lihat arah produk <span aria-hidden="true">↗</span></a></section></section>${templateSection()}`
}
export function templateSection() {
 return `<section class="principles-section"><p class="eyebrow">Operating templates</p><h2>Unduh. Pakai.<br>Review setiap minggu.</h2><section class="download-list"><a class="button" href="/downloads/daily-close.csv" download data-template="daily_close">Daily close sheet ↓</a><a class="button" href="/downloads/weekly-review.csv" download data-template="weekly_review">Weekly operations review ↓</a><a class="button" href="/downloads/utility-weekly-review.csv" download data-template="utility_review">Weekly utility review ↓</a><a class="button" href="/downloads/target-omzet-sheet.csv" download data-template="target_revenue">Target omzet sheet ↓</a><a class="button" href="/downloads/barber-onboarding.html">Checklist penutupan ↗</a></section><p>Template kosong, bukan bukti pelanggan. Jangan unggah catatan pribadi atau angka bisnis aktual ke repository publik.</p></section>`
}
export function toolPage(id:ToolId) {
 const t=toolDefinitions.find(t=>t.id===id)!
 return `<header class="page-hero"><p class="eyebrow"><a href="/tools">HOLBERY / Free Tools</a> / Barber</p><h1>${t.intro}</h1><p>${t.description}</p><span class="tag">GRATIS · TANPA AKUN · HASIL DI BROWSER</span></header>
 <section class="tool-panel" data-tool="${t.id}" aria-labelledby="calculator-heading"><h2 id="calculator-heading">${t.title}</h2><p>Isi seluruh kolom. Gunakan rupiah bulat; masukkan 0 jika sesuai. Angka input dan hasil tidak dikirim atau disimpan aplikasi.</p><form id="${t.formId}" class="utility-form" novalidate><section class="tool-form">${t.fields.map(([dom,label,key,max])=>`<section class="field"><label for="${dom}">${label}</label><input id="${dom}" name="${key}" type="number" min="0" max="${max}" step="1" inputmode="numeric" required autocomplete="off"></section>`).join('')}</section><button class="button button-primary" type="submit">${t.id==='daily_close'?'Hitung penutupan harian':t.id==='target_revenue'?'Hitung target omzet':'Hitung break-even'}</button> <button class="button" type="reset">Kosongkan</button><p id="calculator-error" class="tool-error" role="alert"></p></form><section id="calculation-result" class="tool-output" tabindex="-1" aria-live="polite" aria-label="Hasil perhitungan" hidden></section><small>${t.limits}</small><button class="button" type="button" data-share-tool>Salin tautan tool</button><p id="share-status" aria-live="polite"></p></section>
 <section class="content-grid"><h2>Cara menghitung.<br>Periksa asumsi.</h2><section><p>${t.explanation}</p><p>${t.example}</p><h3>${t.faq}</h3><p>${t.answer}</p><p>Contoh di atas ilustratif, bukan catatan pelanggan atau bukti hasil usaha. Hasil matematis bukan bukti bisnis tervalidasi.</p></section></section>
 <section class="principles-section"><p class="eyebrow">Utility selanjutnya</p><section class="download-list">${toolDefinitions.filter(other=>other.id!==id).map(other=>`<a class="button" href="/tools/barber/${other.slug}" data-next-tool="${other.id}">${other.title} ↗</a>`).join('')}</section></section>${templateSection()}
 <section class="contact-strip"><section><h2>Perlu menjalankan rutin?<br>Bukan hanya menghitung.</h2><p>Barber Revenue Starter System COMPLETE adalah produk yang sudah ada.<br>Tidak wajib membeli untuk menggunakan tool; belum ada klaim hasil bisnis terverifikasi.</p><a class="text-link" href="/store/direct/products/barber-revenue-starter-system" data-product-cta>Lihat produk yang relevan ↗</a></section></section><script type="module" src="/static/utility-tool.js"></script>`
}
export function measurementPreference() {
 return `<aside class="measurement-preference" aria-label="Pilihan pengukuran"><p>Pengukuran penggunaan opsional: kirim jenis interaksi saja, bukan angka input, hasil, email atau identitas pelanggan. Default mati. Preferensi berlaku di sesi tab ini selama 30 menit.</p><button type="button" class="button" data-measurement="enable">Izinkan pengukuran anonim</button> <button type="button" class="button" data-measurement="disable">Matikan pengukuran</button><p data-measurement-status role="status">Pengukuran mati. Semua tool tetap berfungsi.</p><script type="module" src="/static/utility-events.js"></script></aside>`
}
